# Generated by Django 4.2 on 2024-05-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_inmueble_arrendador_alter_inmueble_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='imagen',
            field=models.ImageField(upload_to=''),
        ),
    ]
