# Generated by Django 4.2 on 2024-05-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_region_comuna_alter_inmueble_comuna'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudarriendo',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='pendiente'),
        ),
        migrations.AddField(
            model_name='solicitudarriendo',
            name='fecha_modificado',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='solicitudarriendo',
            name='fecha_solicitud',
            field=models.DateField(auto_now_add=True, default='2024-05-07'),
            preserve_default=False,
        ),
    ]
