# Generated by Django 4.2 on 2024-05-07 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_solicitudarriendo_fecha_modificado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='descripcion',
            field=models.TextField(max_length=1000),
        ),
    ]
